# Generated by Django 4.1 on 2022-11-22 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anónimo', max_length=200, verbose_name='Nombre')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='E-mail')),
                ('topic', models.CharField(max_length=300, verbose_name='Tema')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Descripción')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Añadir Imagen (Opcional)')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link de referencia (Opcional)')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss', models.CharField(max_length=1000, verbose_name='Discusión')),
                ('forum', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Foro.forum', verbose_name='Foro')),
            ],
        ),
    ]
