# Generated by Django 4.1 on 2022-11-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='header_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name='Añadir Imagen (Opcional)'),
        ),
    ]
